### PR TITLE
release: v1.3.2

### PR DESCRIPTION
**Pull request by dizco**

### CODE REVIEW

**Comment by troels-athenas** [comment]
Anyone could review this? Would love to upgrade to React 18, and I need this :)

**Review by daiky00 — DISMISSED** [review]
LGTM

**Comment by daiky00** [comment]
@dizco Thanks for this great package. When are you releasing this? I am doing `npm install --force` only because of this package haven't been updated it will be nice if you merge this and update the package on npm thank you so much.

**Comment by dizco** [comment]
@daiky00 yes sorry. I had some issues on my machine when I was trying to package the new version and never had the time to fix it yet. Will try again sometime next week

**Pull request merged**
