### PR TITLE
Fix typescript errors with children prop

### PR DESCRIPTION
**Pull request by gintunas**

### CODE REVIEW

**Comment by dizco** [comment]
Hi, I'm not sure I understand the context of this PR. What error were you getting?

**Comment by gintunas** [comment]
> Hi, I'm not sure I understand the context of this PR. What error were you getting?

I was trying to solve typescript error of types not matching. However, I found the fix with this package resolution:
image

**Comment by dizco** [comment]
Resolution found

**Comment by asiniy** [comment]
@dizco he got an error where you put `className`, `onScroll` or another prop:

```
      <ScrollableFeed
        className={style.messageList}
      >
```

Error log:

```
TS2322: Type '{ children: Element[]; className: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ScrollableFeed> & Pick<Readonly<ScrollableFeedProps>, never> & InexactPartial<...> & InexactPartial<...>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ScrollableFeed> & Pick<Readonly<ScrollableFeedProps>, never> & InexactPartial<...> & InexactPartial<...>'
```

**Pull request closed without merging**
